version: '2.1'
services: 
    airflow:
        build: './docker/airflow'
        restart: 'always'
        container_name: 'airflow'
    ports:
        - 8080:8080
    healthcheck:
        test: [ "CMD", "nc", "-z", "airflow", "8080" ]
        timeout: 45s
        interval: 10s
        retries: 10